### ISSUE TITLE
How to validate our data?

### ISSUE THREAD

**Issue by diva1012** [pefi1011/wikiEditHistoryProject#3]

**Comment by diva1012** [comment]
We can use the wikipedia edit information and compare it with our results. 

Most edited articles:  (editFileFrequency)
https://en.wikipedia.org/wiki/Wikipedia:Most_frequently_edited_pages

Most active user:
https://en.wikipedia.org/wiki/Wikipedia:List_of_Wikipedians_by_number_of_edits/5001%E2%80%9310000

Edits: 
https://en.wikipedia.org/wiki/Wikipedia:Edit_count

**Comment by pefi1011** [comment]
done
