### ISSUE TITLE
Output files are maybe weird=

### ISSUE THREAD

**Issue by pefi1011** [pefi1011/wikiEditHistoryProject#4]
Schau mal bitte, von manchen Funktionen bekomm ich 8 Datein (da es 8 threads gab) und dazu sind die Ergebnisse über mehrere Datein verteilt..wie können wir es hinkriegen, eine output Datei von "userEditTimeCount" zu bekommen?

![screen shot 2015-07-06 at 23 19 42](https://cloud.githubusercontent.com/assets/2700828/8533456/881151de-2435-11e5-9f86-852e87bc737c.png)

**Comment by diva1012** [comment]
wie führe ich mein job aus? melde dich irgendwo :D

2015-07-06 23:18 GMT+02:00 Filip notifications@github.com:

**Comment by pefi1011** [comment]
we will do post processing
